version: '2'
services:
    redis:
        image: redis:6
        container_name: jetlinks-ce-redis
        ports:
            - "6379:6379"
        volumes:
            - "./data/redis:/data"
        command: redis-server --appendonly yes
        environment:
            - TZ=Asia/Shanghai
    postgres:
        image: timescale/timescaledb:latest-pg16
        container_name: jetlinks-postgres-16
        ports:
            - "5432:5432"
        volumes:
            - "./data/postgres:/var/lib/postgresql/data"
        environment:
            POSTGRES_PASSWORD: jetlinks
            POSTGRES_DB: jetlinks
            POSTGRES_HOST_AUTH_METHOD: trust
            TZ: Asia/Shanghai